# -*- coding: utf-8 -*-
"""ASSIGNMENT.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WFs8bRf3hsdMEPUJxTEXqjWWYSZYhhbF
"""

# Program to input and display a birthday
from datetime import datetime

# Ask the user to enter their birthday in the format YYYY-MM-DD
birthday_str = input("Enter your birthday (YYYY-MM-DD): ")

# Convert the input string into a date object
try:
    birthday = datetime.strptime(birthday_str, "%Y-%m-%d")
    # Print the birthday in a formatted way
    print(f"Your birthday is: {birthday.strftime('%B %d, %Y')}")
except ValueError:
    print("Invalid date format! Please enter in YYYY-MM-DD format.")